/*
 * yellow_data.c - immutable Pokemon Yellow data tables (ROM bank 4).
 *
 * Base stats/names/moves/items derived from pret/pokered via the
 * kasbuunk/Pokemon (MIT) generated tables; Yellow-specific catch
 * rates (Pikachu, Kadabra, Dragonair, Dragonite) cross-checked
 * against PKHeX personal_y. See NOTICE for attribution.
 *
 * Strings are stored as ASCII char arrays; name accessors copy
 * them into caller buffers so no pointer crosses a switched bank.
 *
 * Generated by tools/generate_yellow_data.py from
 * kasbuunk/Pokemon @ ac72f04af1026b4023015c239b34730b8cccb15e and
 * kwsch/PKHeX @ e0e63bc87837ad2d9c8f8fda4efdbf5f2933db08 (reference only). Do not edit.
 */

#include "yellow.h"

#include "yellow_data.h"
#ifdef __SDCC
#pragma bank 4
#endif

/* species names by Dex number 1..151 (slot 0 unused) */
const char yellow_species_names[YELLOW_SPECIES_COUNT + 1][13] = {
    "?????",
    "BULBASAUR",  /* 1 */
    "IVYSAUR",  /* 2 */
    "VENUSAUR",  /* 3 */
    "CHARMANDER",  /* 4 */
    "CHARMELEON",  /* 5 */
    "CHARIZARD",  /* 6 */
    "SQUIRTLE",  /* 7 */
    "WARTORTLE",  /* 8 */
    "BLASTOISE",  /* 9 */
    "CATERPIE",  /* 10 */
    "METAPOD",  /* 11 */
    "BUTTERFREE",  /* 12 */
    "WEEDLE",  /* 13 */
    "KAKUNA",  /* 14 */
    "BEEDRILL",  /* 15 */
    "PIDGEY",  /* 16 */
    "PIDGEOTTO",  /* 17 */
    "PIDGEOT",  /* 18 */
    "RATTATA",  /* 19 */
    "RATICATE",  /* 20 */
    "SPEAROW",  /* 21 */
    "FEAROW",  /* 22 */
    "EKANS",  /* 23 */
    "ARBOK",  /* 24 */
    "PIKACHU",  /* 25 */
    "RAICHU",  /* 26 */
    "SANDSHREW",  /* 27 */
    "SANDSLASH",  /* 28 */
    "NIDORAN(F)",  /* 29 */
    "NIDORINA",  /* 30 */
    "NIDOQUEEN",  /* 31 */
    "NIDORAN(M)",  /* 32 */
    "NIDORINO",  /* 33 */
    "NIDOKING",  /* 34 */
    "CLEFAIRY",  /* 35 */
    "CLEFABLE",  /* 36 */
    "VULPIX",  /* 37 */
    "NINETALES",  /* 38 */
    "JIGGLYPUFF",  /* 39 */
    "WIGGLYTUFF",  /* 40 */
    "ZUBAT",  /* 41 */
    "GOLBAT",  /* 42 */
    "ODDISH",  /* 43 */
    "GLOOM",  /* 44 */
    "VILEPLUME",  /* 45 */
    "PARAS",  /* 46 */
    "PARASECT",  /* 47 */
    "VENONAT",  /* 48 */
    "VENOMOTH",  /* 49 */
    "DIGLETT",  /* 50 */
    "DUGTRIO",  /* 51 */
    "MEOWTH",  /* 52 */
    "PERSIAN",  /* 53 */
    "PSYDUCK",  /* 54 */
    "GOLDUCK",  /* 55 */
    "MANKEY",  /* 56 */
    "PRIMEAPE",  /* 57 */
    "GROWLITHE",  /* 58 */
    "ARCANINE",  /* 59 */
    "POLIWAG",  /* 60 */
    "POLIWHIRL",  /* 61 */
    "POLIWRATH",  /* 62 */
    "ABRA",  /* 63 */
    "KADABRA",  /* 64 */
    "ALAKAZAM",  /* 65 */
    "MACHOP",  /* 66 */
    "MACHOKE",  /* 67 */
    "MACHAMP",  /* 68 */
    "BELLSPROUT",  /* 69 */
    "WEEPINBELL",  /* 70 */
    "VICTREEBEL",  /* 71 */
    "TENTACOOL",  /* 72 */
    "TENTACRUEL",  /* 73 */
    "GEODUDE",  /* 74 */
    "GRAVELER",  /* 75 */
    "GOLEM",  /* 76 */
    "PONYTA",  /* 77 */
    "RAPIDASH",  /* 78 */
    "SLOWPOKE",  /* 79 */
    "SLOWBRO",  /* 80 */
    "MAGNEMITE",  /* 81 */
    "MAGNETON",  /* 82 */
    "FARFETCH'D",  /* 83 */
    "DODUO",  /* 84 */
    "DODRIO",  /* 85 */
    "SEEL",  /* 86 */
    "DEWGONG",  /* 87 */
    "GRIMER",  /* 88 */
    "MUK",  /* 89 */
    "SHELLDER",  /* 90 */
    "CLOYSTER",  /* 91 */
    "GASTLY",  /* 92 */
    "HAUNTER",  /* 93 */
    "GENGAR",  /* 94 */
    "ONIX",  /* 95 */
    "DROWZEE",  /* 96 */
    "HYPNO",  /* 97 */
    "KRABBY",  /* 98 */
    "KINGLER",  /* 99 */
    "VOLTORB",  /* 100 */
    "ELECTRODE",  /* 101 */
    "EXEGGCUTE",  /* 102 */
    "EXEGGUTOR",  /* 103 */
    "CUBONE",  /* 104 */
    "MAROWAK",  /* 105 */
    "HITMONLEE",  /* 106 */
    "HITMONCHAN",  /* 107 */
    "LICKITUNG",  /* 108 */
    "KOFFING",  /* 109 */
    "WEEZING",  /* 110 */
    "RHYHORN",  /* 111 */
    "RHYDON",  /* 112 */
    "CHANSEY",  /* 113 */
    "TANGELA",  /* 114 */
    "KANGASKHAN",  /* 115 */
    "HORSEA",  /* 116 */
    "SEADRA",  /* 117 */
    "GOLDEEN",  /* 118 */
    "SEAKING",  /* 119 */
    "STARYU",  /* 120 */
    "STARMIE",  /* 121 */
    "MR.MIME",  /* 122 */
    "SCYTHER",  /* 123 */
    "JYNX",  /* 124 */
    "ELECTABUZZ",  /* 125 */
    "MAGMAR",  /* 126 */
    "PINSIR",  /* 127 */
    "TAUROS",  /* 128 */
    "MAGIKARP",  /* 129 */
    "GYARADOS",  /* 130 */
    "LAPRAS",  /* 131 */
    "DITTO",  /* 132 */
    "EEVEE",  /* 133 */
    "VAPOREON",  /* 134 */
    "JOLTEON",  /* 135 */
    "FLAREON",  /* 136 */
    "PORYGON",  /* 137 */
    "OMANYTE",  /* 138 */
    "OMASTAR",  /* 139 */
    "KABUTO",  /* 140 */
    "KABUTOPS",  /* 141 */
    "AERODACTYL",  /* 142 */
    "SNORLAX",  /* 143 */
    "ARTICUNO",  /* 144 */
    "ZAPDOS",  /* 145 */
    "MOLTRES",  /* 146 */
    "DRATINI",  /* 147 */
    "DRAGONAIR",  /* 148 */
    "DRAGONITE",  /* 149 */
    "MEWTWO",  /* 150 */
    "MEW",  /* 151 */
};

/* base stats by Dex number 1..151 (slot 0 zeroed); catch rates are
 * the Yellow cartridge values (Pikachu 163, Kadabra 96,
 * Dragonair 27, Dragonite 9) */
const YellowBaseStats yellow_base_stats_table[YELLOW_SPECIES_COUNT + 1] = {
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 45, 49, 49, 45, 65, 22, 3, 45, 64, 3 },  /* BULBASAUR */
    { 60, 62, 63, 60, 80, 22, 3, 45, 141, 3 },  /* IVYSAUR */
    { 80, 82, 83, 80, 100, 22, 3, 45, 208, 3 },  /* VENUSAUR */
    { 39, 52, 43, 65, 50, 20, 20, 45, 65, 3 },  /* CHARMANDER */
    { 58, 64, 58, 80, 65, 20, 20, 45, 142, 3 },  /* CHARMELEON */
    { 78, 84, 78, 100, 85, 20, 2, 45, 209, 3 },  /* CHARIZARD */
    { 44, 48, 65, 43, 50, 21, 21, 45, 66, 3 },  /* SQUIRTLE */
    { 59, 63, 80, 58, 65, 21, 21, 45, 143, 3 },  /* WARTORTLE */
    { 79, 83, 100, 78, 85, 21, 21, 45, 210, 3 },  /* BLASTOISE */
    { 45, 30, 35, 45, 20, 7, 7, 255, 53, 0 },  /* CATERPIE */
    { 50, 20, 55, 30, 25, 7, 7, 120, 72, 0 },  /* METAPOD */
    { 60, 45, 50, 70, 80, 7, 2, 45, 160, 0 },  /* BUTTERFREE */
    { 40, 35, 30, 50, 20, 7, 3, 255, 52, 0 },  /* WEEDLE */
    { 45, 25, 50, 35, 25, 7, 3, 120, 71, 0 },  /* KAKUNA */
    { 65, 80, 40, 75, 45, 7, 3, 45, 159, 0 },  /* BEEDRILL */
    { 40, 45, 40, 56, 35, 0, 2, 255, 55, 3 },  /* PIDGEY */
    { 63, 60, 55, 71, 50, 0, 2, 120, 113, 3 },  /* PIDGEOTTO */
    { 83, 80, 75, 91, 70, 0, 2, 45, 172, 3 },  /* PIDGEOT */
    { 30, 56, 35, 72, 25, 0, 0, 255, 57, 0 },  /* RATTATA */
    { 55, 81, 60, 97, 50, 0, 0, 90, 116, 0 },  /* RATICATE */
    { 40, 60, 30, 70, 31, 0, 2, 255, 58, 0 },  /* SPEAROW */
    { 65, 90, 65, 100, 61, 0, 2, 90, 162, 0 },  /* FEAROW */
    { 35, 60, 44, 55, 40, 3, 3, 255, 62, 0 },  /* EKANS */
    { 60, 85, 69, 80, 65, 3, 3, 90, 147, 0 },  /* ARBOK */
    { 35, 55, 30, 90, 50, 23, 23, 163, 82, 0 },  /* PIKACHU */
    { 60, 90, 55, 100, 90, 23, 23, 75, 122, 0 },  /* RAICHU */
    { 50, 75, 85, 40, 30, 4, 4, 255, 93, 0 },  /* SANDSHREW */
    { 75, 100, 110, 65, 55, 4, 4, 90, 163, 0 },  /* SANDSLASH */
    { 55, 47, 52, 41, 40, 3, 3, 235, 59, 3 },  /* NIDORAN(F) */
    { 70, 62, 67, 56, 55, 3, 3, 120, 117, 3 },  /* NIDORINA */
    { 90, 82, 87, 76, 75, 3, 4, 45, 194, 3 },  /* NIDOQUEEN */
    { 46, 57, 40, 50, 40, 3, 3, 235, 60, 3 },  /* NIDORAN(M) */
    { 61, 72, 57, 65, 55, 3, 3, 120, 118, 3 },  /* NIDORINO */
    { 81, 92, 77, 85, 75, 3, 4, 45, 195, 3 },  /* NIDOKING */
    { 70, 45, 48, 35, 60, 0, 0, 150, 68, 4 },  /* CLEFAIRY */
    { 95, 70, 73, 60, 85, 0, 0, 25, 129, 4 },  /* CLEFABLE */
    { 38, 41, 40, 65, 65, 20, 20, 190, 63, 0 },  /* VULPIX */
    { 73, 76, 75, 100, 100, 20, 20, 75, 178, 0 },  /* NINETALES */
    { 115, 45, 20, 20, 25, 0, 0, 170, 76, 4 },  /* JIGGLYPUFF */
    { 140, 70, 45, 45, 50, 0, 0, 50, 109, 4 },  /* WIGGLYTUFF */
    { 40, 45, 35, 55, 40, 3, 2, 255, 54, 0 },  /* ZUBAT */
    { 75, 80, 70, 90, 75, 3, 2, 90, 171, 0 },  /* GOLBAT */
    { 45, 50, 55, 30, 75, 22, 3, 255, 78, 3 },  /* ODDISH */
    { 60, 65, 70, 40, 85, 22, 3, 120, 132, 3 },  /* GLOOM */
    { 75, 80, 85, 50, 100, 22, 3, 45, 184, 3 },  /* VILEPLUME */
    { 35, 70, 55, 25, 55, 7, 22, 190, 70, 0 },  /* PARAS */
    { 60, 95, 80, 30, 80, 7, 22, 75, 128, 0 },  /* PARASECT */
    { 60, 55, 50, 45, 40, 7, 3, 190, 75, 0 },  /* VENONAT */
    { 70, 65, 60, 90, 90, 7, 3, 75, 138, 0 },  /* VENOMOTH */
    { 10, 55, 25, 95, 45, 4, 4, 255, 81, 0 },  /* DIGLETT */
    { 35, 80, 50, 120, 70, 4, 4, 50, 153, 0 },  /* DUGTRIO */
    { 40, 45, 35, 90, 40, 0, 0, 255, 69, 0 },  /* MEOWTH */
    { 65, 70, 60, 115, 65, 0, 0, 90, 148, 0 },  /* PERSIAN */
    { 50, 52, 48, 55, 50, 21, 21, 190, 80, 0 },  /* PSYDUCK */
    { 80, 82, 78, 85, 80, 21, 21, 75, 174, 0 },  /* GOLDUCK */
    { 40, 80, 35, 70, 35, 1, 1, 190, 74, 0 },  /* MANKEY */
    { 65, 105, 60, 95, 60, 1, 1, 75, 149, 0 },  /* PRIMEAPE */
    { 55, 70, 45, 60, 50, 20, 20, 190, 91, 5 },  /* GROWLITHE */
    { 90, 110, 80, 95, 80, 20, 20, 75, 213, 5 },  /* ARCANINE */
    { 40, 50, 40, 90, 40, 21, 21, 255, 77, 3 },  /* POLIWAG */
    { 65, 65, 65, 90, 50, 21, 21, 120, 131, 3 },  /* POLIWHIRL */
    { 90, 85, 95, 70, 70, 21, 1, 45, 185, 3 },  /* POLIWRATH */
    { 25, 20, 15, 90, 105, 24, 24, 200, 73, 3 },  /* ABRA */
    { 40, 35, 30, 105, 120, 24, 24, 96, 145, 3 },  /* KADABRA */
    { 55, 50, 45, 120, 135, 24, 24, 50, 186, 3 },  /* ALAKAZAM */
    { 70, 80, 50, 35, 35, 1, 1, 180, 88, 3 },  /* MACHOP */
    { 80, 100, 70, 45, 50, 1, 1, 90, 146, 3 },  /* MACHOKE */
    { 90, 130, 80, 55, 65, 1, 1, 45, 193, 3 },  /* MACHAMP */
    { 50, 75, 35, 40, 70, 22, 3, 255, 84, 3 },  /* BELLSPROUT */
    { 65, 90, 50, 55, 85, 22, 3, 120, 151, 3 },  /* WEEPINBELL */
    { 80, 105, 65, 70, 100, 22, 3, 45, 191, 3 },  /* VICTREEBEL */
    { 40, 40, 35, 70, 100, 21, 3, 190, 105, 5 },  /* TENTACOOL */
    { 80, 70, 65, 100, 120, 21, 3, 60, 205, 5 },  /* TENTACRUEL */
    { 40, 80, 100, 20, 30, 5, 4, 255, 86, 3 },  /* GEODUDE */
    { 55, 95, 115, 35, 45, 5, 4, 120, 134, 3 },  /* GRAVELER */
    { 80, 110, 130, 45, 55, 5, 4, 45, 177, 3 },  /* GOLEM */
    { 50, 85, 55, 90, 65, 20, 20, 190, 152, 0 },  /* PONYTA */
    { 65, 100, 70, 105, 80, 20, 20, 60, 192, 0 },  /* RAPIDASH */
    { 90, 65, 65, 15, 40, 21, 24, 190, 99, 0 },  /* SLOWPOKE */
    { 95, 75, 110, 30, 80, 21, 24, 75, 164, 0 },  /* SLOWBRO */
    { 25, 35, 70, 45, 95, 23, 23, 190, 89, 0 },  /* MAGNEMITE */
    { 50, 60, 95, 70, 120, 23, 23, 60, 161, 0 },  /* MAGNETON */
    { 52, 65, 55, 60, 58, 0, 2, 45, 94, 0 },  /* FARFETCH'D */
    { 35, 85, 45, 75, 35, 0, 2, 190, 96, 0 },  /* DODUO */
    { 60, 110, 70, 100, 60, 0, 2, 45, 158, 0 },  /* DODRIO */
    { 65, 45, 55, 45, 70, 21, 21, 190, 100, 0 },  /* SEEL */
    { 90, 70, 80, 70, 95, 21, 25, 75, 176, 0 },  /* DEWGONG */
    { 80, 80, 50, 25, 40, 3, 3, 190, 90, 0 },  /* GRIMER */
    { 105, 105, 75, 50, 65, 3, 3, 75, 157, 0 },  /* MUK */
    { 30, 65, 100, 40, 45, 21, 21, 190, 97, 5 },  /* SHELLDER */
    { 50, 95, 180, 70, 85, 21, 25, 60, 203, 5 },  /* CLOYSTER */
    { 30, 35, 30, 80, 100, 8, 3, 190, 95, 3 },  /* GASTLY */
    { 45, 50, 45, 95, 115, 8, 3, 90, 126, 3 },  /* HAUNTER */
    { 60, 65, 60, 110, 130, 8, 3, 45, 190, 3 },  /* GENGAR */
    { 35, 45, 160, 70, 30, 5, 4, 45, 108, 0 },  /* ONIX */
    { 60, 48, 45, 42, 90, 24, 24, 190, 102, 0 },  /* DROWZEE */
    { 85, 73, 70, 67, 115, 24, 24, 75, 165, 0 },  /* HYPNO */
    { 30, 105, 90, 50, 25, 21, 21, 225, 115, 0 },  /* KRABBY */
    { 55, 130, 115, 75, 50, 21, 21, 60, 206, 0 },  /* KINGLER */
    { 40, 30, 50, 100, 55, 23, 23, 190, 103, 0 },  /* VOLTORB */
    { 60, 50, 70, 140, 80, 23, 23, 60, 150, 0 },  /* ELECTRODE */
    { 60, 40, 80, 40, 60, 22, 24, 90, 98, 5 },  /* EXEGGCUTE */
    { 95, 95, 85, 55, 125, 22, 24, 45, 212, 5 },  /* EXEGGUTOR */
    { 50, 50, 95, 35, 40, 4, 4, 190, 87, 0 },  /* CUBONE */
    { 60, 80, 110, 45, 50, 4, 4, 75, 124, 0 },  /* MAROWAK */
    { 50, 120, 53, 87, 35, 1, 1, 45, 139, 0 },  /* HITMONLEE */
    { 50, 105, 79, 76, 35, 1, 1, 45, 140, 0 },  /* HITMONCHAN */
    { 90, 55, 75, 30, 60, 0, 0, 45, 127, 0 },  /* LICKITUNG */
    { 40, 65, 95, 35, 60, 3, 3, 190, 114, 0 },  /* KOFFING */
    { 65, 90, 120, 60, 85, 3, 3, 60, 173, 0 },  /* WEEZING */
    { 80, 85, 95, 25, 30, 4, 5, 120, 135, 5 },  /* RHYHORN */
    { 105, 130, 120, 40, 45, 4, 5, 60, 204, 5 },  /* RHYDON */
    { 250, 5, 5, 50, 105, 0, 0, 30, 255, 4 },  /* CHANSEY */
    { 65, 55, 115, 60, 100, 22, 22, 45, 166, 0 },  /* TANGELA */
    { 105, 95, 80, 90, 40, 0, 0, 45, 175, 0 },  /* KANGASKHAN */
    { 30, 40, 70, 60, 70, 21, 21, 225, 83, 0 },  /* HORSEA */
    { 55, 65, 95, 85, 95, 21, 21, 75, 155, 0 },  /* SEADRA */
    { 45, 67, 60, 63, 50, 21, 21, 225, 111, 0 },  /* GOLDEEN */
    { 80, 92, 65, 68, 80, 21, 21, 60, 170, 0 },  /* SEAKING */
    { 30, 45, 55, 85, 70, 21, 21, 225, 106, 5 },  /* STARYU */
    { 60, 75, 85, 115, 100, 21, 24, 60, 207, 5 },  /* STARMIE */
    { 40, 45, 65, 90, 100, 24, 24, 45, 136, 0 },  /* MR.MIME */
    { 70, 110, 80, 105, 55, 7, 2, 45, 187, 0 },  /* SCYTHER */
    { 65, 50, 35, 95, 95, 25, 24, 45, 137, 0 },  /* JYNX */
    { 65, 83, 57, 105, 85, 23, 23, 45, 156, 0 },  /* ELECTABUZZ */
    { 65, 95, 57, 93, 85, 20, 20, 45, 167, 0 },  /* MAGMAR */
    { 65, 125, 100, 85, 55, 7, 7, 45, 200, 5 },  /* PINSIR */
    { 75, 100, 95, 110, 70, 0, 0, 45, 211, 5 },  /* TAUROS */
    { 20, 10, 55, 80, 20, 21, 21, 255, 20, 5 },  /* MAGIKARP */
    { 95, 125, 79, 81, 100, 21, 2, 45, 214, 5 },  /* GYARADOS */
    { 130, 85, 80, 60, 95, 21, 25, 45, 219, 5 },  /* LAPRAS */
    { 48, 48, 48, 48, 48, 0, 0, 35, 61, 0 },  /* DITTO */
    { 55, 55, 50, 55, 65, 0, 0, 45, 92, 0 },  /* EEVEE */
    { 130, 65, 60, 65, 110, 21, 21, 45, 196, 0 },  /* VAPOREON */
    { 65, 65, 60, 130, 110, 23, 23, 45, 197, 0 },  /* JOLTEON */
    { 65, 130, 60, 65, 110, 20, 20, 45, 198, 0 },  /* FLAREON */
    { 65, 60, 70, 40, 75, 0, 0, 45, 130, 0 },  /* PORYGON */
    { 35, 40, 100, 35, 90, 5, 21, 45, 120, 0 },  /* OMANYTE */
    { 70, 60, 125, 55, 115, 5, 21, 45, 199, 0 },  /* OMASTAR */
    { 30, 80, 90, 55, 45, 5, 21, 45, 119, 0 },  /* KABUTO */
    { 60, 115, 105, 80, 70, 5, 21, 45, 201, 0 },  /* KABUTOPS */
    { 80, 105, 65, 130, 60, 5, 2, 45, 202, 5 },  /* AERODACTYL */
    { 160, 110, 65, 30, 65, 0, 0, 25, 154, 5 },  /* SNORLAX */
    { 90, 85, 100, 85, 125, 25, 2, 3, 215, 5 },  /* ARTICUNO */
    { 90, 90, 85, 100, 125, 23, 2, 3, 216, 5 },  /* ZAPDOS */
    { 90, 100, 90, 90, 125, 20, 2, 3, 217, 5 },  /* MOLTRES */
    { 41, 64, 45, 50, 50, 26, 26, 45, 67, 5 },  /* DRATINI */
    { 61, 84, 65, 70, 70, 26, 26, 27, 144, 5 },  /* DRAGONAIR */
    { 91, 134, 95, 80, 100, 26, 2, 9, 218, 5 },  /* DRAGONITE */
    { 106, 110, 90, 130, 154, 24, 24, 3, 220, 5 },  /* MEWTWO */
    { 100, 100, 100, 100, 100, 24, 24, 45, 64, 3 },  /* MEW */
};

/* internal species index -> Dex number (0 = invalid); 256 entries */
const uint8_t yellow_index_to_dex_table[256] = {
      0, 112, 115,  32,  35,  21, 100,  34,  80,   2, 103, 108, 102,  88,  94,  29,
     31, 104, 111, 131,  59, 151, 130,  90,  72,  92, 123, 120,   9, 127, 114,   0,
      0,  58,  95,  22,  16,  79,  64,  75, 113,  67, 122, 106, 107,  24,  47,  54,
     96,  76,   0, 126,   0, 125,  82, 109,   0,  56,  86,  50, 128,   0,   0,   0,
     83,  48, 149,   0,   0,   0,  84,  60, 124, 146, 144, 145, 132,  52,  98,   0,
      0,   0,  37,  38,  25,  26,   0,   0, 147, 148, 140, 141, 116, 117,   0,   0,
     27,  28, 138, 139,  39,  40, 133, 136, 135, 134,  66,  41,  23,  46,  61,  62,
     13,  14,  15,   0,  85,  57,  51,  49,  87,   0,   0,  10,  11,  12,  68,   0,
     55,  97,  42, 150, 143, 129,   0,   0,  89,   0,  99,  91,   0, 101,  36, 110,
     53, 105,   0,  93,  63,  65,  17,  18, 121,   1,   3,  73,   0, 118, 119,   0,
      0,   0,   0,  77,  78,  19,  20,  33,  30,  74, 137, 142,   0,  81,   0,   0,
      4,   7,   5,   8,   6,   0,   0,   0,   0,  43,  44,  45,  69,  70,  71,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
};

/* Dex number -> internal species index (slot 0 unused); 152 entries */
const uint8_t yellow_dex_to_index_table[YELLOW_SPECIES_COUNT + 1] = {
    0x00, 0x99, 0x09, 0x9A, 0xB0, 0xB2, 0xB4, 0xB1, 0xB3, 0x1C, 0x7B, 0x7C, 0x7D, 0x70, 0x71, 0x72,
    0x24, 0x96, 0x97, 0xA5, 0xA6, 0x05, 0x23, 0x6C, 0x2D, 0x54, 0x55, 0x60, 0x61, 0x0F, 0xA8, 0x10,
    0x03, 0xA7, 0x07, 0x04, 0x8E, 0x52, 0x53, 0x64, 0x65, 0x6B, 0x82, 0xB9, 0xBA, 0xBB, 0x6D, 0x2E,
    0x41, 0x77, 0x3B, 0x76, 0x4D, 0x90, 0x2F, 0x80, 0x39, 0x75, 0x21, 0x14, 0x47, 0x6E, 0x6F, 0x94,
    0x26, 0x95, 0x6A, 0x29, 0x7E, 0xBC, 0xBD, 0xBE, 0x18, 0x9B, 0xA9, 0x27, 0x31, 0xA3, 0xA4, 0x25,
    0x08, 0xAD, 0x36, 0x40, 0x46, 0x74, 0x3A, 0x78, 0x0D, 0x88, 0x17, 0x8B, 0x19, 0x93, 0x0E, 0x22,
    0x30, 0x81, 0x4E, 0x8A, 0x06, 0x8D, 0x0C, 0x0A, 0x11, 0x91, 0x2B, 0x2C, 0x0B, 0x37, 0x8F, 0x12,
    0x01, 0x28, 0x1E, 0x02, 0x5C, 0x5D, 0x9D, 0x9E, 0x1B, 0x98, 0x2A, 0x1A, 0x48, 0x35, 0x33, 0x1D,
    0x3C, 0x85, 0x16, 0x13, 0x4C, 0x66, 0x69, 0x68, 0x67, 0xAA, 0x62, 0x63, 0x5A, 0x5B, 0xAB, 0x84,
    0x4A, 0x4B, 0x49, 0x58, 0x59, 0x42, 0x83, 0x15,
};

/* moves by id 1..165 (slot 0 zeroed) */
const YellowMoveInfo yellow_moves_table[YELLOW_MOVE_COUNT + 1] = {
    { "", 0, 0, 0, 0 },
    { "POUND", 40, 0, 255, 35 },
    { "KARATE CHOP", 50, 0, 255, 25 },
    { "DOUBLESLAP", 15, 0, 216, 10 },
    { "COMET PUNCH", 18, 0, 216, 15 },
    { "MEGA PUNCH", 80, 0, 216, 20 },
    { "PAY DAY", 40, 0, 255, 20 },
    { "FIRE PUNCH", 75, 20, 255, 15 },
    { "ICE PUNCH", 75, 25, 255, 15 },
    { "THUNDERPUNCH", 75, 23, 255, 15 },
    { "SCRATCH", 40, 0, 255, 35 },
    { "VICEGRIP", 55, 0, 255, 30 },
    { "GUILLOTINE", 1, 0, 76, 5 },
    { "RAZOR WIND", 80, 0, 191, 10 },
    { "SWORDS DANCE", 0, 0, 255, 30 },
    { "CUT", 50, 0, 242, 30 },
    { "GUST", 40, 0, 255, 35 },
    { "WING ATTACK", 35, 2, 255, 35 },
    { "WHIRLWIND", 0, 0, 216, 20 },
    { "FLY", 70, 2, 242, 15 },
    { "BIND", 15, 0, 191, 20 },
    { "SLAM", 80, 0, 191, 20 },
    { "VINE WHIP", 35, 22, 255, 10 },
    { "STOMP", 65, 0, 255, 20 },
    { "DOUBLE KICK", 30, 1, 255, 30 },
    { "MEGA KICK", 120, 0, 191, 5 },
    { "JUMP KICK", 70, 1, 242, 25 },
    { "ROLLING KICK", 60, 1, 216, 15 },
    { "SAND-ATTACK", 0, 0, 255, 15 },
    { "HEADBUTT", 70, 0, 255, 15 },
    { "HORN ATTACK", 65, 0, 255, 25 },
    { "FURY ATTACK", 15, 0, 216, 20 },
    { "HORN DRILL", 1, 0, 76, 5 },
    { "TACKLE", 35, 0, 242, 35 },
    { "BODY SLAM", 85, 0, 255, 15 },
    { "WRAP", 15, 0, 216, 20 },
    { "TAKE DOWN", 90, 0, 216, 20 },
    { "THRASH", 90, 0, 255, 20 },
    { "DOUBLE-EDGE", 100, 0, 255, 15 },
    { "TAIL WHIP", 0, 0, 255, 30 },
    { "POISON STING", 15, 3, 255, 35 },
    { "TWINEEDLE", 25, 7, 255, 20 },
    { "PIN MISSILE", 14, 7, 216, 20 },
    { "LEER", 0, 0, 255, 30 },
    { "BITE", 60, 0, 255, 25 },
    { "GROWL", 0, 0, 255, 40 },
    { "ROAR", 0, 0, 255, 20 },
    { "SING", 0, 0, 140, 15 },
    { "SUPERSONIC", 0, 0, 140, 20 },
    { "SONICBOOM", 1, 0, 229, 20 },
    { "DISABLE", 0, 0, 140, 20 },
    { "ACID", 40, 3, 255, 30 },
    { "EMBER", 40, 20, 255, 25 },
    { "FLAMETHROWER", 95, 20, 255, 15 },
    { "MIST", 0, 25, 255, 30 },
    { "WATER GUN", 40, 21, 255, 25 },
    { "HYDRO PUMP", 120, 21, 204, 5 },
    { "SURF", 95, 21, 255, 15 },
    { "ICE BEAM", 95, 25, 255, 10 },
    { "BLIZZARD", 120, 25, 229, 5 },
    { "PSYBEAM", 65, 24, 255, 20 },
    { "BUBBLEBEAM", 65, 21, 255, 20 },
    { "AURORA BEAM", 65, 25, 255, 20 },
    { "HYPER BEAM", 150, 0, 229, 5 },
    { "PECK", 35, 2, 255, 35 },
    { "DRILL PECK", 80, 2, 255, 20 },
    { "SUBMISSION", 80, 1, 204, 25 },
    { "LOW KICK", 50, 1, 229, 20 },
    { "COUNTER", 1, 1, 255, 20 },
    { "SEISMIC TOSS", 1, 1, 255, 20 },
    { "STRENGTH", 80, 0, 255, 15 },
    { "ABSORB", 20, 22, 255, 20 },
    { "MEGA DRAIN", 40, 22, 255, 10 },
    { "LEECH SEED", 0, 22, 229, 10 },
    { "GROWTH", 0, 0, 255, 40 },
    { "RAZOR LEAF", 55, 22, 242, 25 },
    { "SOLARBEAM", 120, 22, 255, 10 },
    { "POISONPOWDER", 0, 3, 191, 35 },
    { "STUN SPORE", 0, 22, 191, 30 },
    { "SLEEP POWDER", 0, 22, 191, 15 },
    { "PETAL DANCE", 70, 22, 255, 20 },
    { "STRING SHOT", 0, 7, 242, 40 },
    { "DRAGON RAGE", 1, 26, 255, 10 },
    { "FIRE SPIN", 15, 20, 178, 15 },
    { "THUNDERSHOCK", 40, 23, 255, 30 },
    { "THUNDERBOLT", 95, 23, 255, 15 },
    { "THUNDER WAVE", 0, 23, 255, 20 },
    { "THUNDER", 120, 23, 178, 10 },
    { "ROCK THROW", 50, 5, 165, 15 },
    { "EARTHQUAKE", 100, 4, 255, 10 },
    { "FISSURE", 1, 4, 76, 5 },
    { "DIG", 100, 4, 255, 10 },
    { "TOXIC", 0, 3, 216, 10 },
    { "CONFUSION", 50, 24, 255, 25 },
    { "PSYCHIC", 90, 24, 255, 10 },
    { "HYPNOSIS", 0, 24, 153, 20 },
    { "MEDITATE", 0, 24, 255, 40 },
    { "AGILITY", 0, 24, 255, 30 },
    { "QUICK ATTACK", 40, 0, 255, 30 },
    { "RAGE", 20, 0, 255, 20 },
    { "TELEPORT", 0, 24, 255, 20 },
    { "NIGHT SHADE", 0, 8, 255, 15 },
    { "MIMIC", 0, 0, 255, 10 },
    { "SCREECH", 0, 0, 216, 40 },
    { "DOUBLE TEAM", 0, 0, 255, 15 },
    { "RECOVER", 0, 0, 255, 20 },
    { "HARDEN", 0, 0, 255, 30 },
    { "MINIMIZE", 0, 0, 255, 20 },
    { "SMOKESCREEN", 0, 0, 255, 20 },
    { "CONFUSE RAY", 0, 8, 255, 10 },
    { "WITHDRAW", 0, 21, 255, 40 },
    { "DEFENSE CURL", 0, 0, 255, 40 },
    { "BARRIER", 0, 24, 255, 30 },
    { "LIGHT SCREEN", 0, 24, 255, 30 },
    { "HAZE", 0, 25, 255, 30 },
    { "REFLECT", 0, 24, 255, 20 },
    { "FOCUS ENERGY", 0, 0, 255, 30 },
    { "BIDE", 0, 0, 255, 10 },
    { "METRONOME", 0, 0, 255, 10 },
    { "MIRROR MOVE", 0, 2, 255, 20 },
    { "SELFDESTRUCT", 130, 0, 255, 5 },
    { "EGG BOMB", 100, 0, 191, 10 },
    { "LICK", 20, 8, 255, 30 },
    { "SMOG", 20, 3, 178, 20 },
    { "SLUDGE", 65, 3, 255, 20 },
    { "BONE CLUB", 65, 4, 216, 20 },
    { "FIRE BLAST", 120, 20, 216, 5 },
    { "WATERFALL", 80, 21, 255, 15 },
    { "CLAMP", 35, 21, 191, 10 },
    { "SWIFT", 60, 0, 255, 20 },
    { "SKULL BASH", 100, 0, 255, 15 },
    { "SPIKE CANNON", 20, 0, 255, 15 },
    { "CONSTRICT", 10, 0, 255, 35 },
    { "AMNESIA", 0, 24, 255, 20 },
    { "KINESIS", 0, 24, 204, 15 },
    { "SOFTBOILED", 0, 0, 255, 10 },
    { "HI JUMP KICK", 85, 1, 229, 20 },
    { "GLARE", 0, 0, 191, 30 },
    { "DREAM EATER", 100, 24, 255, 15 },
    { "POISON GAS", 0, 3, 140, 40 },
    { "BARRAGE", 15, 0, 216, 20 },
    { "LEECH LIFE", 20, 7, 255, 15 },
    { "LOVELY KISS", 0, 0, 191, 10 },
    { "SKY ATTACK", 140, 2, 229, 5 },
    { "TRANSFORM", 0, 0, 255, 10 },
    { "BUBBLE", 20, 21, 255, 30 },
    { "DIZZY PUNCH", 70, 0, 255, 10 },
    { "SPORE", 0, 22, 255, 15 },
    { "FLASH", 0, 0, 178, 20 },
    { "PSYWAVE", 1, 24, 204, 15 },
    { "SPLASH", 0, 0, 255, 40 },
    { "ACID ARMOR", 0, 3, 255, 40 },
    { "CRABHAMMER", 90, 21, 216, 10 },
    { "EXPLOSION", 170, 0, 255, 5 },
    { "FURY SWIPES", 18, 0, 204, 15 },
    { "BONEMERANG", 50, 4, 229, 10 },
    { "REST", 0, 24, 255, 10 },
    { "ROCK SLIDE", 75, 5, 229, 10 },
    { "HYPER FANG", 80, 0, 229, 15 },
    { "SHARPEN", 0, 0, 255, 30 },
    { "CONVERSION", 0, 0, 255, 30 },
    { "TRI ATTACK", 80, 0, 255, 10 },
    { "SUPER FANG", 1, 0, 229, 10 },
    { "SLASH", 70, 0, 255, 20 },
    { "SUBSTITUTE", 0, 0, 255, 10 },
    { "STRUGGLE", 50, 0, 255, 10 },
};

/* item names by id; "" marks invalid/glitch ids */
const char yellow_item_names[256][13] = {
    "",  /* 0x00 */
    "MASTER BALL",  /* 0x01 */
    "ULTRA BALL",  /* 0x02 */
    "GREAT BALL",  /* 0x03 */
    "POKe BALL",  /* 0x04 */
    "TOWN MAP",  /* 0x05 */
    "BICYCLE",  /* 0x06 */
    "?????",  /* 0x07 */
    "SAFARI BALL",  /* 0x08 */
    "POKeDEX",  /* 0x09 */
    "MOON STONE",  /* 0x0A */
    "ANTIDOTE",  /* 0x0B */
    "BURN HEAL",  /* 0x0C */
    "ICE HEAL",  /* 0x0D */
    "AWAKENING",  /* 0x0E */
    "PARLYZ HEAL",  /* 0x0F */
    "FULL RESTORE",  /* 0x10 */
    "MAX POTION",  /* 0x11 */
    "HYPER POTION",  /* 0x12 */
    "SUPER POTION",  /* 0x13 */
    "POTION",  /* 0x14 */
    "BOULDERBADGE",  /* 0x15 */
    "CASCADEBADGE",  /* 0x16 */
    "THUNDERBADGE",  /* 0x17 */
    "RAINBOWBADGE",  /* 0x18 */
    "SOULBADGE",  /* 0x19 */
    "MARSHBADGE",  /* 0x1A */
    "VOLCANOBADGE",  /* 0x1B */
    "EARTHBADGE",  /* 0x1C */
    "ESCAPE ROPE",  /* 0x1D */
    "REPEL",  /* 0x1E */
    "OLD AMBER",  /* 0x1F */
    "FIRE STONE",  /* 0x20 */
    "THUNDERSTONE",  /* 0x21 */
    "WATER STONE",  /* 0x22 */
    "HP UP",  /* 0x23 */
    "PROTEIN",  /* 0x24 */
    "IRON",  /* 0x25 */
    "CARBOS",  /* 0x26 */
    "CALCIUM",  /* 0x27 */
    "RARE CANDY",  /* 0x28 */
    "DOME FOSSIL",  /* 0x29 */
    "HELIX FOSSIL",  /* 0x2A */
    "SECRET KEY",  /* 0x2B */
    "?????",  /* 0x2C */
    "BIKE VOUCHER",  /* 0x2D */
    "X ACCURACY",  /* 0x2E */
    "LEAF STONE",  /* 0x2F */
    "CARD KEY",  /* 0x30 */
    "NUGGET",  /* 0x31 */
    "PP UP",  /* 0x32 */
    "POKe DOLL",  /* 0x33 */
    "FULL HEAL",  /* 0x34 */
    "REVIVE",  /* 0x35 */
    "MAX REVIVE",  /* 0x36 */
    "GUARD SPEC.",  /* 0x37 */
    "SUPER REPEL",  /* 0x38 */
    "MAX REPEL",  /* 0x39 */
    "DIRE HIT",  /* 0x3A */
    "COIN",  /* 0x3B */
    "FRESH WATER",  /* 0x3C */
    "SODA POP",  /* 0x3D */
    "LEMONADE",  /* 0x3E */
    "S.S.TICKET",  /* 0x3F */
    "GOLD TEETH",  /* 0x40 */
    "X ATTACK",  /* 0x41 */
    "X DEFEND",  /* 0x42 */
    "X SPEED",  /* 0x43 */
    "X SPECIAL",  /* 0x44 */
    "COIN CASE",  /* 0x45 */
    "OAK's PARCEL",  /* 0x46 */
    "ITEMFINDER",  /* 0x47 */
    "SILPH SCOPE",  /* 0x48 */
    "POKe FLUTE",  /* 0x49 */
    "LIFT KEY",  /* 0x4A */
    "EXP.ALL",  /* 0x4B */
    "OLD ROD",  /* 0x4C */
    "GOOD ROD",  /* 0x4D */
    "SUPER ROD",  /* 0x4E */
    "PP UP",  /* 0x4F */
    "ETHER",  /* 0x50 */
    "MAX ETHER",  /* 0x51 */
    "ELIXER",  /* 0x52 */
    "MAX ELIXER",  /* 0x53 */
    "B2F",  /* 0x54 */
    "B1F",  /* 0x55 */
    "1F",  /* 0x56 */
    "2F",  /* 0x57 */
    "3F",  /* 0x58 */
    "4F",  /* 0x59 */
    "5F",  /* 0x5A */
    "6F",  /* 0x5B */
    "7F",  /* 0x5C */
    "8F",  /* 0x5D */
    "9F",  /* 0x5E */
    "10F",  /* 0x5F */
    "11F",  /* 0x60 */
    "B4F",  /* 0x61 */
    "",  /* 0x62 */
    "",  /* 0x63 */
    "",  /* 0x64 */
    "",  /* 0x65 */
    "",  /* 0x66 */
    "",  /* 0x67 */
    "",  /* 0x68 */
    "",  /* 0x69 */
    "",  /* 0x6A */
    "",  /* 0x6B */
    "",  /* 0x6C */
    "",  /* 0x6D */
    "",  /* 0x6E */
    "",  /* 0x6F */
    "",  /* 0x70 */
    "",  /* 0x71 */
    "",  /* 0x72 */
    "",  /* 0x73 */
    "",  /* 0x74 */
    "",  /* 0x75 */
    "",  /* 0x76 */
    "",  /* 0x77 */
    "",  /* 0x78 */
    "",  /* 0x79 */
    "",  /* 0x7A */
    "",  /* 0x7B */
    "",  /* 0x7C */
    "",  /* 0x7D */
    "",  /* 0x7E */
    "",  /* 0x7F */
    "",  /* 0x80 */
    "",  /* 0x81 */
    "",  /* 0x82 */
    "",  /* 0x83 */
    "",  /* 0x84 */
    "",  /* 0x85 */
    "",  /* 0x86 */
    "",  /* 0x87 */
    "",  /* 0x88 */
    "",  /* 0x89 */
    "",  /* 0x8A */
    "",  /* 0x8B */
    "",  /* 0x8C */
    "",  /* 0x8D */
    "",  /* 0x8E */
    "",  /* 0x8F */
    "",  /* 0x90 */
    "",  /* 0x91 */
    "",  /* 0x92 */
    "",  /* 0x93 */
    "",  /* 0x94 */
    "",  /* 0x95 */
    "",  /* 0x96 */
    "",  /* 0x97 */
    "",  /* 0x98 */
    "",  /* 0x99 */
    "",  /* 0x9A */
    "",  /* 0x9B */
    "",  /* 0x9C */
    "",  /* 0x9D */
    "",  /* 0x9E */
    "",  /* 0x9F */
    "",  /* 0xA0 */
    "",  /* 0xA1 */
    "",  /* 0xA2 */
    "",  /* 0xA3 */
    "",  /* 0xA4 */
    "",  /* 0xA5 */
    "",  /* 0xA6 */
    "",  /* 0xA7 */
    "",  /* 0xA8 */
    "",  /* 0xA9 */
    "",  /* 0xAA */
    "",  /* 0xAB */
    "",  /* 0xAC */
    "",  /* 0xAD */
    "",  /* 0xAE */
    "",  /* 0xAF */
    "",  /* 0xB0 */
    "",  /* 0xB1 */
    "",  /* 0xB2 */
    "",  /* 0xB3 */
    "",  /* 0xB4 */
    "",  /* 0xB5 */
    "",  /* 0xB6 */
    "",  /* 0xB7 */
    "",  /* 0xB8 */
    "",  /* 0xB9 */
    "",  /* 0xBA */
    "",  /* 0xBB */
    "",  /* 0xBC */
    "",  /* 0xBD */
    "",  /* 0xBE */
    "",  /* 0xBF */
    "",  /* 0xC0 */
    "",  /* 0xC1 */
    "",  /* 0xC2 */
    "",  /* 0xC3 */
    "HM01",  /* 0xC4 */
    "HM02",  /* 0xC5 */
    "HM03",  /* 0xC6 */
    "HM04",  /* 0xC7 */
    "HM05",  /* 0xC8 */
    "TM01",  /* 0xC9 */
    "TM02",  /* 0xCA */
    "TM03",  /* 0xCB */
    "TM04",  /* 0xCC */
    "TM05",  /* 0xCD */
    "TM06",  /* 0xCE */
    "TM07",  /* 0xCF */
    "TM08",  /* 0xD0 */
    "TM09",  /* 0xD1 */
    "TM10",  /* 0xD2 */
    "TM11",  /* 0xD3 */
    "TM12",  /* 0xD4 */
    "TM13",  /* 0xD5 */
    "TM14",  /* 0xD6 */
    "TM15",  /* 0xD7 */
    "TM16",  /* 0xD8 */
    "TM17",  /* 0xD9 */
    "TM18",  /* 0xDA */
    "TM19",  /* 0xDB */
    "TM20",  /* 0xDC */
    "TM21",  /* 0xDD */
    "TM22",  /* 0xDE */
    "TM23",  /* 0xDF */
    "TM24",  /* 0xE0 */
    "TM25",  /* 0xE1 */
    "TM26",  /* 0xE2 */
    "TM27",  /* 0xE3 */
    "TM28",  /* 0xE4 */
    "TM29",  /* 0xE5 */
    "TM30",  /* 0xE6 */
    "TM31",  /* 0xE7 */
    "TM32",  /* 0xE8 */
    "TM33",  /* 0xE9 */
    "TM34",  /* 0xEA */
    "TM35",  /* 0xEB */
    "TM36",  /* 0xEC */
    "TM37",  /* 0xED */
    "TM38",  /* 0xEE */
    "TM39",  /* 0xEF */
    "TM40",  /* 0xF0 */
    "TM41",  /* 0xF1 */
    "TM42",  /* 0xF2 */
    "TM43",  /* 0xF3 */
    "TM44",  /* 0xF4 */
    "TM45",  /* 0xF5 */
    "TM46",  /* 0xF6 */
    "TM47",  /* 0xF7 */
    "TM48",  /* 0xF8 */
    "TM49",  /* 0xF9 */
    "TM50",  /* 0xFA */
    "TM51",  /* 0xFB */
    "TM52",  /* 0xFC */
    "TM53",  /* 0xFD */
    "TM54",  /* 0xFE */
    "TM55",  /* 0xFF */
};


/* Gen 1 type names by id 0..26 */
const char yellow_type_names[27][10] = {
    "NORMAL",  /* 0 */
    "FIGHTING",  /* 1 */
    "FLYING",  /* 2 */
    "POISON",  /* 3 */
    "GROUND",  /* 4 */
    "ROCK",  /* 5 */
    "BIRD",  /* 6 */
    "BUG",  /* 7 */
    "GHOST",  /* 8 */
    "",  /* 9 */
    "",  /* 10 */
    "",  /* 11 */
    "",  /* 12 */
    "",  /* 13 */
    "",  /* 14 */
    "",  /* 15 */
    "",  /* 16 */
    "",  /* 17 */
    "",  /* 18 */
    "",  /* 19 */
    "FIRE",  /* 20 */
    "WATER",  /* 21 */
    "GRASS",  /* 22 */
    "ELECTRIC",  /* 23 */
    "PSYCHIC",  /* 24 */
    "ICE",  /* 25 */
    "DRAGON",  /* 26 */
};

/* Copy a NUL-terminated table string into buf, truncating to buflen-1
 * chars plus terminator. */
static void copy_name(const char *src, char *buf, uint8_t buflen)
{
    uint8_t i;

    if (buflen == 0) {
        return;
    }
    for (i = 0; i + 1 < buflen && src[i] != '\0'; i++) {
        buf[i] = src[i];
    }
    buf[i] = '\0';
}

void yellow_species_name(uint8_t dex, char *buf, uint8_t buflen) YELLOW_BANKED
{
    if (dex < 1 || dex > YELLOW_SPECIES_COUNT) {
        copy_name("", buf, buflen);
        return;
    }
    copy_name(yellow_species_names[dex], buf, buflen);
}

void yellow_move_name(uint8_t move_id, char *buf, uint8_t buflen) YELLOW_BANKED
{
    if (move_id < 1 || move_id > YELLOW_MOVE_COUNT) {
        copy_name("", buf, buflen);
        return;
    }
    copy_name(yellow_moves_table[move_id].name, buf, buflen);
}

void yellow_item_name(uint8_t item_id, char *buf, uint8_t buflen) YELLOW_BANKED
{
    copy_name(yellow_item_names[item_id], buf, buflen);
}

void yellow_type_name(uint8_t type_id, char *buf, uint8_t buflen) YELLOW_BANKED
{
    if (type_id > 26) {
        copy_name("", buf, buflen);
        return;
    }
    copy_name(yellow_type_names[type_id], buf, buflen);
}

uint8_t yellow_item_valid(uint8_t item_id) YELLOW_BANKED
{
    if (item_id >= 196u && item_id <= 250u) return 1;
    if (item_id < 1u || item_id > 83u) return 0;
    if (item_id >= 21u && item_id <= 28u) return 0;
    return item_id != 7u && item_id != 8u && item_id != 9u &&
           item_id != 44u && item_id != 50u && item_id != 59u;
}

uint8_t yellow_move_valid(uint8_t move_id) YELLOW_BANKED
{
    return move_id >= 1 && move_id <= YELLOW_MOVE_COUNT;
}

uint8_t yellow_move_power(uint8_t move_id) YELLOW_BANKED
{
    if (!yellow_move_valid(move_id)) {
        return 0;
    }
    return yellow_moves_table[move_id].power;
}

uint8_t yellow_move_type(uint8_t move_id) YELLOW_BANKED
{
    if (!yellow_move_valid(move_id)) {
        return 0;
    }
    return yellow_moves_table[move_id].type_id;
}

uint8_t yellow_move_accuracy(uint8_t move_id) YELLOW_BANKED
{
    if (!yellow_move_valid(move_id)) {
        return 0;
    }
    return yellow_moves_table[move_id].accuracy;
}

uint8_t yellow_move_base_pp(uint8_t move_id) YELLOW_BANKED
{
    if (!yellow_move_valid(move_id)) {
        return 0;
    }
    return yellow_moves_table[move_id].base_pp;
}

void yellow_base_stats(uint8_t dex, YellowBaseStats *out) YELLOW_BANKED
{
    if (dex < 1 || dex > YELLOW_SPECIES_COUNT) {
        out->hp = 0;
        out->attack = 0;
        out->defense = 0;
        out->speed = 0;
        out->special = 0;
        out->type1 = 0;
        out->type2 = 0;
        out->catch_rate = 0;
        out->exp_yield = 0;
        out->growth_rate = 0;
        return;
    }
    *out = yellow_base_stats_table[dex];
}

uint8_t yellow_dex_to_index(uint8_t dex) YELLOW_BANKED
{
    if (dex < 1 || dex > YELLOW_SPECIES_COUNT) {
        return 0;
    }
    return yellow_dex_to_index_table[dex];
}

uint8_t yellow_index_to_dex(uint8_t species_index) YELLOW_BANKED
{
    return yellow_index_to_dex_table[species_index];
}
